# Generated by Django 6.0.6 on 2026-07-05 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('personel', '0002_positionpermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gorev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('aciklama', models.TextField(blank=True)),
                ('baslangic_tarihi', models.DateField()),
                ('bitis_tarihi', models.DateField()),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('tamamlandi', 'Tamamlandı')], default='bekliyor', max_length=20)),
                ('tamamlanma_tarihi', models.DateTimeField(blank=True, null=True)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('atanan_personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorevler', to='personel.employee')),
                ('atayan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atadigi_gorevler', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorevler', to='core.tenant')),
            ],
            options={
                'ordering': ['baslangic_tarihi'],
                'indexes': [models.Index(fields=['tenant', 'atanan_personel'], name='planlama_go_tenant__485796_idx')],
            },
        ),
    ]
