# Generated by Django 6.0.6 on 2026-07-04 21:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar')),
                ('entry_type', models.CharField(choices=[('alacak', 'Alacak'), ('borc', 'Borç')], max_length=10, verbose_name='İşlem Tipi')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='İşlem Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
