# Generated by Django 6.0.6 on 2026-07-04 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('muhasebe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeentry',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Şirket'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financeentry',
            name='entry_type',
            field=models.CharField(choices=[('alacak', 'Alacak'), ('borc', 'Borc')], max_length=10, verbose_name='İşlem Tipi'),
        ),
    ]
